[package]
name = "kmath"
version = "0.1.0"
edition = "2018"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]

[dev-dependencies]
bencher = "0.1.5"
glam = "0.14.0"

[[bench]]
name = "bench"
harness = false